name: Destroy

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.3
  TERRAFORM_VERSION: 1.8.3

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: us-east4
      TF_VAR_project_id: sonicscribe-42
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      TF_VAR_access_code: ${{ secrets.ACCESS_CODE }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa_key.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Set up Google Cloud credentials
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" -backend-config="prefix=${{ secrets.TF_BACKEND_PREFIX }}"
        working-directory: terraform

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: terraform

      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve
        working-directory: terraform
